version: '3.7'
services:
  ingest:
    image: ${REGISTRY:-docker.io}/cnxta/ion-ingest
    ports:
      - target: 8080
        published: 9043
        protocol: tcp
      - target: 10050
        published: 10053
        protocol: tcp
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
    configs:
      - source: transform_config
        target: /configs/transform_config.yml
    command:
      - "--spring.config.additional-location=file:/configs/transform_config.yml"
networks:
  cdr:
    external: true
configs:
  transform_config:
    file: ./configs/transform_config.yml