version: '3.7'
services:
  ingest:
    image: ${IMAGE_PREFIX}cnxta/ion-ingest
    ports:
      - target: 8080
        published: 9040
        protocol: tcp
      - target: 10050
        published: 10050
        protocol: tcp
    environment:
      TRANSFORM_HOST: ${TRANSFORM_HOST}
      RETRIEVE_HOST: ${RETRIEVE_HOST}
      S3_PROVIDER_URL: ${S3_PROVIDER_URL}
      S3_REGION: ${S3_REGION}    
    networks:
      - cdr
    deploy:
      restart_policy:
        condition: any
    secrets:
     - source: s3_secret
       target: /secrets/ingest/s3_secret.sec
     - source: s3_access
       target: /secrets/ingest/s3_access.sec
    command:
      - "--s3.secret.file=/secrets/ingest/s3_secret.sec"
      - "--s3.access.file=/secrets/ingest/s3_access.sec"
networks:
  cdr:
    external: true
secrets:
  s3_secret:
    file: s3_secret.sec
  s3_access:
    file: s3_access.sec