version: '3.7'

services:
  ingest:
    image: cnxta/ion-ingest
    environment:
      TRANSFORM_HOST: ${TRANSFORM_HOST}
      RETRIEVE_HOST: ${RETRIEVE_HOST}
      S3_PROVIDER_URL: ${S3_PROVIDER_URL}
      S3_REGION: ${S3_REGION} 
    secrets:
     - source: s3_secret
       target: /secrets/ingest/s3_secret.sec
     - source: s3_access
       target: /secrets/ingest/s3_access.sec
secrets:
  # Directories are relative to the master compose file
  s3_secret:
    file: deployments/local-minio/secrets/minio_secret.notsec
  s3_access:
    file: deployments/local-minio/secrets/minio_access.notsec