version: 2.1
jobs:
  Full Build:
    docker: &image
      - image: circleci/openjdk:11-jdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Building
          command: |
            ./gradlew clean build --info
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  OWASP:
    docker: *image
    steps:
      - checkout
      - run:
          name: OWASP
          command: |
            ./gradlew dependencyCheckAnalyze --info
workflows:
  version: 2.1
  default:
    jobs:
      - Full Build
      - OWASP